language: minimal

services: docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker -v && docker-compose -v
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f ./docker-compose-build.yaml build --push
  - docker-compose push
